name: Gitleaks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2.2.0
      with:
          fetch-depth: 0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

